# Generated by Django 4.2.7 on 2023-11-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instagram_access_token', models.CharField(max_length=100)),
                ('twitter_access_token', models.CharField(max_length=100)),
                ('facebook_access_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('accounts',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.CharField(max_length=100)),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_page.user')),
            ],
        ),
    ]
